### ISSUE TITLE
Cross-compile and release for Scala 2.11.x

### ISSUE THREAD

**Issue by Asamsig** [dobrynya/reajames#38]
Would be awesome to be able to use this library on Scala 2.11.x

**Comment by dobrynya** [comment]
I'm not sure how to build for different versions of scala using gradle as a build tool. I have to research it first. You can compile the library for 2.11.x and store it locally or deploy to somewhere as a work around.

**Comment by dobrynya** [comment]
It is required to change JmsSender.notifySubscribers to the following implementation to be compiled in 2.11.x
```scala
private[reajames] def notifySubscribers(cause: Option[Throwable]) =
    subscribers.forEach(new Consumer[CompleteSubscription] {
      def accept(subscription: CompleteSubscription) = subscription.completeWith(cause)
    })
```

**Comment by Asamsig** [comment]
Yeah that is what I've done so far, but I'm working on migrating my whole project to 2.12, just have to fix a few local dependencies. So my need for a 2.11.x release is fading. 👍

**Comment by dobrynya** [comment]
Alexander can you help me with cross-compiling sources for 2.11 & 2.12. Actually I was trying to use scala multiversion plugin for gradle. It seems that it's quite incompatible with bintray plugin used for publishing artifacts to jcenter repository. So currently I have no idea how to achieve the goal. Maybe you have some experience or thoughts on the above.

**Comment by Asamsig** [comment]
I've only worked with multiversioning in SBT, so I could help migrate to SBT if you wish, but you have quite a lot of tasks, which would make this difficult. Do you have any experience with SBT?

**Comment by dobrynya** [comment]
Yes, I have a little. Frankly speaking I don't like sbt as it is a strange stuff from my perspective :)
So if you are not interested any more in compiling for 2.11 we can close this issue. What do you say?

**Comment by Asamsig** [comment]
Fine with me. :)
